common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'




urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

inthepark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    # path('main/', include('mains.urls')),
    path('map/', TemplateView.as_view(template_name='map.html'), name="map"),
    path('common/', include('common.urls')),
    path('posts/', include('posts.urls')),
    # path('', include('')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import TemplateView
from posts import views
from posts.models import Park_number

app_name = "posts"

urlpatterns = [
    path('<str:area_name>/lists/', views.p_lists, name='lists'),
    path('<int:park_num>/detail/', views.p_detail, name="detail"),
    path('makedb/', views.p_makedb, name='makedb'),
    path('write_post/<int:p_idx>', views.write_post, name='write_post'),
]

common/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.


class Park_number(models.Model):
    p_local_name = models.CharField('공원위치지역', max_length=100)
    p_idx = models.IntegerField('공원번호')

    def __str__(self):
        return self.p_local_name


class Post(models.Model):
    p_idx = models.ForeignKey(Park_number, on_delete=models.CASCADE, related_name='posts')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    starpoint = models.IntegerField('별점1~5', null=True, blank=True,
                                    validators=[MinValueValidator(0), MaxValueValidator(5)])
    contents = models.TextField('글내용', max_length=500)
    images = models.ImageField(blank=True, upload_to="images", null=True)

    def __str__(self):
        return self.contents

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

posts/forms.py
from django import forms
from posts.models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['starpoint', 'contents', 'images']

common/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'signup.html', {'form': form})

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from posts.models import Park_number, Post
from posts.forms import PostForm
from urllib.request import urlopen
import json
# Create your views here.


def p_lists(request, area_name):
    return render(request, 'lists.html', {'area_name': area_name})


def p_detail(request, park_num):
    park_post = get_object_or_404(Park_number, p_idx=park_num)
    return render(request, 'detail.html', {'park_post': park_post})


def p_makedb(request):
    url = "http://openapi.seoul.go.kr:8088/534e6b7475686a6538386154554170/json/SearchParkInfoService/1/138/"
    responseBody = urlopen(url).read().decode('utf-8')
    jsonArray = json.loads(responseBody)
    InfosArray = jsonArray.get("SearchParkInfoService")
    resultArray = InfosArray.get("row")
    for i in resultArray:
        parknum_form = Park_number(p_local_name=i.get("P_ZONE"), p_idx=i.get("P_IDX"))
        parknum_form.save()

    return redirect('/')


def write_post(request, p_idx):
    park_post = get_object_or_404(Park_number, p_idx=p_idx)
    if request.method == 'POST':
        if request.FILES:
            post = Post(p_idx=park_post, author=request.user, images=request.FILES['images'])
        else:
            post = Post(p_idx=park_post, author=request.user, images=None)
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post_form.save()
            path = '/posts/{}/detail'.format(p_idx)
            return  redirect(path)
        # post_form = Post(p_idx=p_idx, author=request.user, starpoint=request.POST['starpoint'], contents=request.POST['contents'], images=request.FILES['images'])
        # post_form.save()
        # return redirect('posts:detail')
    else:
        post_form = PostForm()

    return render(request, 'write.html', {'post_form': post_form})

common/templates/form_error.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

common/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>InthePark-Login</title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
	<!-- 합쳐지고 최소화된 최신 CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
	<!-- 부가적인 테마 -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
	<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

	<link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">

	<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
		#username{
		display : block;
		margin : 0 auto;
		width:400px;
		height:60px;
		}
		#password{
		display : block;
		margin : 0 auto;
		width:400px;
		height:60px;
		}
		#my_btn{
		border-top-right-radius: 5px;
		border-bottom-right-radius: 5px;
		border-top-left-radius: 5px;
		border-bottom-left-radius: 5px;
		margin : 0 auto;
		width:400px;
		height:60px;
		border: 1px solid skyblue;
		background-color: rgba(0,0,0,0);
		color: skyblue;
		padding: 5px;
		}
		.my-box {
		border-top-right-radius: 5px;
		border-bottom-right-radius: 5px;
		border-top-left-radius: 5px;
		border-bottom-left-radius: 5px;
		width:500px;
		margin : 0 auto;
		border:1px solid;
		border-color: white;
		padding:10px;
		background-color: white;
		line-color: white;
		}
    </style>
  </head>

  <body class="text-center" style="background-image:url('/static/img/background.jpg'); background-size:cover">
  <div style="height:100px"></div>
  <div class="my-box">
  <form method="post" class="post-form" action="{% url 'common:login' %}">
      {% csrf_token %}
	  <h1 class="h3 mb-3 font-weight-normal">Account Sign</h1>

	  <label for="username"></label>
	  <input type="text"  name="username" id="username" class="form-control" placeholder="USER ID" value="{{ form.username.value|default_if_none:'' }}">

	  <label for="password"></label>
	  <input type="password"  name="password" id="password" class="form-control" placeholder="Password" value="{{ form.password.value|default_if_none:'' }}">
	  <div>
		  <a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </a>
	  </div>

	  <button id="my_btn" type="submit">Sign in</button>
  </form>
  </div>
  <p class="mt-5 mb-3 text-muted">&copy; inthehpark</p>
</body>
</html>

inthepark/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/css/main.css">
<!--===============================================================================================-->
    <title>InthePark-Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="static/css/cover.css" rel="stylesheet">


</head>
<body class="">
<!--<div class="cover-container d-flex w-100 h-100 p-3 " id="divPosition">-->
<!--    <header class="masthead mb-auto">-->
<!--        <div class="">-->
<!--            <h3 class="masthead-brand">Myblog</h3>-->
<!--        </div>-->
<!--    </header>-->

<!--    <main role="main" class="inner cover">-->
<!--        <h1 class="cover-heading">Welcome to my Blog.</h1>-->
<!--        {% if user.is_authenticated %}-->
<!--        <a class="lead" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>-->
<!--        {% else %}-->
<!--        <p class="lead"><a href="{%url 'common:login' %}">Sign in</a></p>-->
<!--        {% endif %}-->
<!--        <p class="lead">-->
<!--            <a href="/map/" class="btn btn-lg btn-secondary">Enter BBS</a>-->
<!--        </p>-->
<!--&lt;!&ndash;        <p class="lead"><a href="{% url 'posts:makedb' %}">make db</a></p>&ndash;&gt;-->
<!--    </main>-->

<!--</div>-->

    <div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">

                {% if user.is_authenticated %}
					<a class="login100-form-title p-b-33" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
					<div class="text-center">
                    	<span class="txt1">
							Go Seoul Map?
						</span>
                    	<a href="/map/" class="txt2 hov1">
							Go
                    	</a>
                	</div>
                {% else %}
				<form  method="post" class="post-form" action="{% url 'common:login' %}">
                    {% csrf_token %}
                    {% include "form_error.html" %}
					<span class="login100-form-title p-b-33">
						Account Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" id="username" placeholder="Username" value="{{ form.username.value|default_if_none:'' }}">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password" id="password" placeholder="Password" value="{{ form.password.value|default_if_none:'' }}">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="container-login100-form-btn m-t-20">
						<button type="submit" class="login100-form-btn">
							Sign in
						</button>
					</div>

					<div class="text-center">
						<span class="txt1">
							Create an account?
						</span>

						<a href="{% url 'common:signup' %}" class="txt2 hov1">
							Sign up
						</a>
					</div>
				</form>
                {% endif %}


			</div>
		</div>
	</div>
<!--===============================================================================================-->
	<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/bootstrap/js/popper.js"></script>
	<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/daterangepicker/moment.min.js"></script>
	<script src="static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="static/js/main.js"></script>
    {% block container %}
    {% endblock %}
</body>
</html>

posts/templates/detail.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="/static/detail/img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="Colorlib">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>InthePark-Detail</title>

	<!-- detail.html head 가져온 것 -->
	<script src="https://code.jquery.com/jquery-2.2.4.min.js"
			integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			crossorigin="anonymous"></script>
	<script src="/static/js/detail.js"></script>
	<!-- 우리는 Bootstrap을 다운로드 방식이 아닌 CDN 방식으로 이용하려고 한다 -->
	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
		  integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
		  crossorigin="anonymous">
	<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=oi19384r8r"></script>

	<style>
		.bd-placeholder-img {
			font-size: 1.125rem;
			text-anchor: middle;
			-webkit-user-select: none;
			-moz-user-select: none;
			-ms-user-select: none;
			user-select: none;
		}

		@media (min-width: 768px) {
			.bd-placeholder-img-lg {
				font-size: 3.5rem;
			}
		}
	</style>
	<!-- detail.html head 가져온 것 -->

	<link href="https://fonts.googleapis.com/css?family=Poppins:300,500,600" rel="stylesheet">
		<!--
		CSS
		============================================= -->
		<link rel="stylesheet" href="/static/detail/css/linearicons.css">
		<link rel="stylesheet" href="/static/detail/css/owl.carousel.css">
		<link rel="stylesheet" href="/static/detail/css/font-awesome.min.css">
		<link rel="stylesheet" href="/static/detail/css/nice-select.css">
		<link rel="stylesheet" href="/static/detail/css/magnific-popup.css">
		<link rel="stylesheet" href="/static/detail/css/bootstrap.css">
		<link rel="stylesheet" href="/static/detail/css/main.css">

		    <style>
				.star-rating {width:304px; }
				.star-rating,.star-rating span {display:inline-block; height:55px; overflow:hidden;
				background:url(/static/img/star.png)no-repeat; }
				.star-rating span{background-position:left bottom; line-height:0; vertical-align:top; }
			</style>
	</head>
	<body style="padding-bottom: 2rem;">
	<nav class="navbar navbar-expand-sm navbar-white bg-green">
  <a class="navbar-brand" href="/">In The Park</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/map/">Map <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Gu list</a>
        <div class="dropdown-menu" aria-labelledby="dropdown03">
          <a class="dropdown-item" href="{% url 'posts:lists' '도봉구' %}">도봉구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '노원구' %}">노원구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '강북구' %}">강북구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '은평구' %}">은평구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '서대문구' %}">서대문구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '종로구' %}">종로구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '성북구' %}">성북구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '중랑구' %}">중랑구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '동대문구' %}">동대문구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '강서구' %}">강서구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '마포구' %}">마포구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '중구' %}">중구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '성동구' %}">성동구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '광진구' %}">광진구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '강동구' %}">강동구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '용산구' %}">용산구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '양천구' %}">양천구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '영등포구' %}">영등포구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '구로구' %}">구로구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '동작구' %}">동작구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '금천구' %}">금천구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '관악구' %}">관악구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '서초구' %}">서초구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '강남구' %}">강남구</a>
          <a class="dropdown-item" href="{% url 'posts:lists' '송파구' %}">송파구</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

	<!-- ajax 호출 -->
	<script>
		$(document).ready(detail_ajax('{{ park_post.p_idx }}'));
	</script>
	<!-- ajax 호출 끝 -->
		<div class="main-wrapper-first">
			<div class="hero-area relative">

				<div class="banner-area">
					<div class="overlay hero-overlay-bg"></div>
					<div class="container">
						<div class="row height align-items-center justify-content-center">
							<div class="col-lg-7">
								<div class="banner-content text-center">
									<img class="img-fluid" src="/static/detail/img/title-img.png" alt="">
									<p class="text-white p-2 mb-30" id="myParkname"
									style="font-size: 50px; font-weight: bold; margin-top: 30px;"></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="main-wrapper">
			<!-- Start About Top Area -->
			<section class="about-top-area">
				<div class="container-fluid">
					<div class="row h-100 justify-content-start align-items-center">
						<div class="col-lg-6 about-left">
							<div class="overlay overlay-bg"></div>

							<!-- 네이버 지도 들어갈 부분 -->
							<div id="map" style="width:450px;height:360px;"></div>


						</div>
						<div class="col-lg-6 about-right pt-30 pb-30">
							<div class="single-desc">
								<span class="icon lnr lnr-rocket"></span>
								<h2 id="myParkaddr"></h2>
								<p id="myParkcontents">

								</p>
							</div>
							<div class="single-desc">
								<span class="icon lnr lnr-sun"></span>
								<h2>주요 시설</h2>
								<p id="myParkequip">

								</p>
<!--								<a id="my_map">길찾기로가기</a>-->
								<input type="button" value="길찾기" class="btn btn-primary" id="my_map"
								>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End About Top Area -->
			<!-- Start Feature Area -->
			<section class="feature-area pt-90 pb-90">
				<div class="container">
					<div>
						<span style="padding-right: 20px; font-size: 35px;">
							Comments
						</span>
						<span style="padding-right: 20px; font-size: 35px;">
							|
						</span>
						<a href="{% url 'posts:write_post' park_post.p_idx %}"
						style="font-size: 25px;">
							댓글쓰러가기
						</a>
					</div>
				</div>
				<div class="container">
					<div class="row h-100 align-items-center" style="margin-left: 0px; margin-top: 20px;
						margin-right: 0px;">

						{% for post in park_post.posts.all %}
						<div style="padding-left: 10px; padding-right: 10px;
						padding-bottom: 20px;" id="list">
							<script>
									var ratingFunction = function() {
										var h2 = $("<h2></h2>").text('{{post.author}}').attr('style',
										'font-size: 25px;')
										$('#list').append(h2)
										var starlist = $("<div></div>").attr('id', 'starlist').attr('style',
										'padding-bottom: 30px;')
    									var div = $("<div></div>").addClass("wrap-star").attr('style',
    									'margin-bottom: 20px;')
    									var in_div = $("<div></div>").addClass("star-rating")
    									var span = $("<span></span>").attr('id', 'star')
    									var percent = {{ post.starpoint }} * 20;
    									span.attr('style', 'width:' + percent + '%');
    									in_div.append(span)
    									div.append(in_div)
    									starlist.append(div)
    									var p = $("<p></p>").text('{{post.contents}}').attr('style',
    									'margin-bottom: 30px; font-size: 20px;')
    									starlist.append(p)
    									{% if post.images %}
    									var img = $("<img />").attr({
    									'src' : '{{post.images.url}}',
    									'width' : 200,
    									'height' : 100,
    									})
    									starlist.append(img)
    									{% endif %}
    									$('#list').append(starlist)
    								}
    								ratingFunction();
								</script>
<!--							<h2>{{ post.author }}</h2>-->
<!--							<div id="starlist">-->
<!--								<p> {{ post.starpoint }} / 5 </p>-->
<!--								<p>{{ post.contents }}</p>-->
<!--								{% if post.images %}-->
<!--								<img src="{{ post.images.url }}" width="200" height="100" />-->
<!--							{% endif %}-->
<!--							</div>-->
						</div>
						{% empty %}
						<p>아직 댓글이 없어요</p>
						{% endfor %}
					</div>
				</div>
			</section>
			<!-- End Feature Area -->

		</div>
		<script src="/static/detail/js/vendor/jquery-2.2.4.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
		<script src="/static/detail/js/vendor/bootstrap.min.js"></script>
		<script src="/static/detail/js/jquery.ajaxchimp.min.js"></script>
		<script src="/static/detail/js/owl.carousel.min.js"></script>
		<script src="/static/detail/js/jquery.nice-select.min.js"></script>
		<script src="/static/detail/js/jquery.magnific-popup.min.js"></script>
		<script src="/static/detail/js/main.js"></script>
	</body>
</html>